export const ROLES = {
  SUPERADMIN: 'SUPERADMIN',
  STORE_ADMIN: 'STORE_ADMIN',
  BARISTA: 'BARISTA',
  CASHIER: 'CASHIER',
  SHIFT_LEAD: 'SHIFT_LEAD',
  MANAGER: 'MANAGER',
};

export const STATUSES = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
  TEMPORARY_CLOSED: 'TEMPORARY_CLOSED',
};

export const ORDER_MODES = {
  PICKUP: 'PICKUP',
  DELIVERY: 'DELIVERY',
  DINEIN: 'DINEIN',
  POS_COUNTER: 'POS_COUNTER',
};

export const ORDER_SOURCES = {
  APP: 'APP',
  POS: 'POS',
};

export const ORDER_STATUSES = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  READY: 'READY',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED',
};

export const TABLE_STATUSES = {
  AVAILABLE: 'AVAILABLE',
  OCCUPIED: 'OCCUPIED',
  RESERVED: 'RESERVED',
  INACTIVE: 'INACTIVE',
};
